on: 
  push:
    branches:
    - 'production'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Build runner
      run: docker build runner -t runner

    - name: Make image
      run: docker run --privileged --rm -v /dev:/dev:ro -v "$PWD":/runner -w /runner -e ALPINE_BRANCH=latest-stable -e ALPINE_MIRROR="http://dl-cdn.alpinelinux.org/alpine" -e ARCH=aarch64 runner ./make-image
    
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*.gz"
        token: ${{ secrets.GITHUB_TOKEN }}